params.pp: Rename client_package_name to client_package, and correctly define it
Leaving this unset leads to problematic consequences if another
module does the same, as both would alias the package to nil.

node bob {
  include heat::client
  include neutron::client
}

Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError:
Cannot alias Package[python-neutronclient] to [nil] at
/etc/puppet/modules/neutron/manifests/client.pp:20; resource
["Package", nil] already declared at
/etc/puppet/modules/heat/manifests/client.pp:17 at
/etc/puppet/modules/neutron/manifests/client.pp:20 on node bob
Warning: Not using cache on failed catalog Error: Could not retrieve
catalog; skipping run

Companion change in puppet-heat: Ib0ae86d7ff406039f4b361a65c2e092d2a321a77

Change-Id: I63266ca8faa807b8aef051b319a06fa323757ceb