Fix dependency cycle issue
Error: Failed to apply catalog: Found 1 dependency cycle

Initially the correct tags was not used for the package
resource in this class. Once added the require on
::neutron::plugins::ml2 and package tag cause cycle
dependecy issue. Removing require ::neutron::plugins::ml2
fixes the issue.


Closes-Bug: #1748435
Change-Id: Ie7bb7d00c606a928b58cdc45e04c4fce45208fe5